

name: unit-testing-learningx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Run Maven
        with:
          command: mvn clean install
      
      - name: Foresight Test Report Uploader
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: ./target/surefire-reports/
